language: node_js
node_js: node
services:
- postgresql
before_script:
- psql -c 'create database palettepicker_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: SPQOK4+Hd91kSDfF3r+jlHmSF814e4lqbCCix/ySsTeV29BKoDi7CCFd3CfPnjm5L/SXhU7xZ1QqMe0+EK63ZGbuipisNNKWeVy+QOiNFR9yzPf865S03RvZGJ0hUeaUTt+o3zpcDtY2skhpndpUpBTzPf9kAstOzbbDXAKzaX5Ln5npPWS/und68xB0kZcgF1CU5+YgxdiuoGiXcSqJBNrgTerte5TqHkbJb8NRzzCVtAjFXXBn3R6jz3hWotyoZ8DTapQoefczgBmelsGM1zr9G9JIKYznLzTuLzNgqwAgvDof0dh7VK01jctSWKOxy7aogopxRn+pUzDY2MZQYRg6beJWCyl95MQDd1iN9m8VdESYzIKwD78OsudWxg1dMekLzlEp4zlvYYHseMa5WGuGdqXmr3EGB/kvyiyAm9coZBOgiq2YxMuWyQ6Iv7j0uAVRCjfG9jgfBTRviCZGyCEPdXeuNOFcAiYx1jXHS/VaQrZGwXzUYDDGlYr7P3oS1nzDvlIHKIysLVOYA7Fd7Uo+KyQRQDsW/HAUhLsvojpZBpkPJvxbTamhJctpjj/LZqrQK93KGTts9SVD/V1TWhTW7P2St376qj7WalkzFGyAwKC2QF+nCVSTznMo2Jd+BbZlpj3QIYVV76DFMuTRcbc4nZfS24fx6lriWYUb1BQ=
  app: stevenspalette
